CREATE TABLE [dbo].[Users]
(
	[Id] INT NOT NULL IDENTITY, 
    [FirstName] VARCHAR(50) NOT NULL, 
    [LastName] VARCHAR(50) NOT NULL, 
    [Email] VARCHAR(100) NOT NULL, 
    [Status] TINYINT NOT NULL CONSTRAINT DF_Users_Status  DEFAULT 0,
    [CreatedTime] DATETIMEOFFSET NOT NULL CONSTRAINT DF_Users_CreatedTime  DEFAULT SYSDATETIMEOFFSET(), 
    [UpdatedTime] DATETIMEOFFSET NULL,
    CONSTRAINT PK_Users PRIMARY KEY CLUSTERED (Id),
    INDEX IX_Email NONCLUSTERED (Email)
)
