CREATE TABLE [dbo].[UsersLogin]
(
	[Id] INT NOT NULL IDENTITY(1,1) CONSTRAINT PK_UsersLogin PRIMARY KEY CLUSTERED, 
    [UserName] VARCHAR(50) NOT NULL, 
    [Password] VARCHAR(100) NOT NULL, 
    [CreatedTime] DATETIMEOFFSET NOT NULL CONSTRAINT DF_UserLogin_CreatedTime  DEFAULT SYSDATETIMEOFFSET(), 
    [UpdatedTime] DATETIMEOFFSET NULL, 
    [LastLoginTime] DATETIMEOFFSET NULL,    
    INDEX IX_UserName NONCLUSTERED (UserName, Password)
)
