CREATE TABLE [dbo].[Groups]
(
	[Id] INT NOT NULL IDENTITY(1,1),
	Name VARCHAR(100),
	Description VARCHAR(500),	
	CreatedTime DATETIMEOFFSET NOT NULL DEFAULT SYSDATETIMEOFFSET(),
	CONSTRAINT PK_ServicesGroup PRIMARY KEY CLUSTERED (Id)
)
